Repository Daniel-W-Innes/SYSC4806-Project-Backend, pull requests merged in 2022-03, with the labels that each got.

#33 Issue #: 30, 31 & 32
  pom.xml
  src/main/java/ca/group20/sysc4806project/config/WebConfig.java
  src/main/java/ca/group20/sysc4806project/controller/SurveyorController.java
  src/main/java/ca/group20/sysc4806project/model/Survey.java
  src/main/java/ca/group20/sysc4806project/model/Surveyor.java
  src/main/java/ca/group20/sysc4806project/model/answer/Answer.java
  src/main/java/ca/group20/sysc4806project/model/answer/NumberAnswer.java
  src/main/java/ca/group20/sysc4806project/model/answer/TextAnswer.java
  src/main/java/ca/group20/sysc4806project/model/question/MultipleChoiceQuestion.java
  src/main/java/ca/group20/sysc4806project/model/question/NumberQuestion.java
  src/main/java/ca/group20/sysc4806project/model/question/Question.java
Labels: bug, enhancement

#35 get survey
  src/main/java/ca/group20/sysc4806project/controller/SurveyorController.java
  src/main/java/ca/group20/sysc4806project/model/Surveyor.java
  src/main/java/ca/group20/sysc4806project/repository/SurveyRepo.java
  src/main/java/ca/group20/sysc4806project/service/SurveyService.java
Labels: enhancement

#36 Doc/marianne/7
  README.md
  documentation/DatabaseSchema_v1.PNG
  documentation/ListOfSurveys.png
  documentation/ModelClassUML_v1.png
  src/main/java/ca/group20/sysc4806project/model/Survey.java
Labels: documentation

#38 cache .m2
  .travis.yml
Labels: enhancement

#42 Display choices for multiple choice questions
  README.md
  docs/DatabaseSchema.PNG
  docs/ListOfSurveys.png
  docs/Models.png
  docs/Models.puml
  documentation/DatabaseSchema_v1.PNG
  documentation/ModelClassUML_v1.png
  src/main/java/ca/group20/sysc4806project/config/DatabaseConfig.java
  src/main/java/ca/group20/sysc4806project/model/Survey.java
  src/main/java/ca/group20/sysc4806project/model/Surveyor.java
  src/main/java/ca/group20/sysc4806project/model/answer/Answer.java
  src/main/java/ca/group20/sysc4806project/model/question/MultipleChoiceQuestion.java
  src/main/java/ca/group20/sysc4806project/model/question/MultipleChoiceType.java
  src/main/java/ca/group20/sysc4806project/model/question/Question.java
Labels: enhancement

#51 Deployment diagram
  docs/Deployment.png
  docs/Deployment.puml
Labels: documentation

#58 Feature/daniel/55
  src/main/java/ca/group20/sysc4806project/controller/RespondentController.java
  src/main/java/ca/group20/sysc4806project/controller/SurveyorController.java
  src/main/java/ca/group20/sysc4806project/model/answer/Answer.java
  src/main/java/ca/group20/sysc4806project/model/answer/NumberAnswer.java
  src/main/java/ca/group20/sysc4806project/model/answer/TextAnswer.java
  src/main/java/ca/group20/sysc4806project/model/question/MultipleChoiceQuestion.java
  src/main/java/ca/group20/sysc4806project/model/question/Question.java
  src/main/java/ca/group20/sysc4806project/model/question/TextAnswerable.java
  src/main/java/ca/group20/sysc4806project/repository/AnswerRepo.java
  src/main/java/ca/group20/sysc4806project/repository/SurveyRepo.java
  src/main/java/ca/group20/sysc4806project/service/AnswerService.java
  src/main/java/ca/group20/sysc4806project/service/AnswerServiceImpl.java
  src/main/java/ca/group20/sysc4806project/service/QuestionService.java
  src/main/java/ca/group20/sysc4806project/service/QuestionServiceImpl.java
  src/main/java/ca/group20/sysc4806project/service/SurveyService.java
  src/main/java/ca/group20/sysc4806project/service/SurveyServiceImpl.java
  src/test/java/ca/group20/sysc4806project/controller/SurveyorControllerTest.java
  src/test/java/ca/group20/sysc4806project/model/answer/AnswerTest.java
  test.http
Labels: enhancement

#59 Answer test
  src/test/java/ca/group20/sysc4806project/controller/RespondentControllerTest.java
  src/test/java/ca/group20/sysc4806project/controller/SurveyorControllerTest.java
Labels: enhancement

#54 Added Authentication & Authorization using Spring Security and enhanced the endpoints to use new exceptions.
  pom.xml
  src/main/java/ca/group20/sysc4806project/config/SecurityConfig.java
  src/main/java/ca/group20/sysc4806project/controller/SurveyorController.java
  src/main/java/ca/group20/sysc4806project/exception/InvalidRoleException.java
  src/main/java/ca/group20/sysc4806project/exception/SurveyorAlreadyExistsException.java
  src/main/java/ca/group20/sysc4806project/filter/CustomAuthenticationFilter.java
  src/main/java/ca/group20/sysc4806project/filter/CustomAuthorizationFilter.java
  src/main/java/ca/group20/sysc4806project/model/Role.java
  src/main/java/ca/group20/sysc4806project/model/Surveyor.java
  src/main/java/ca/group20/sysc4806project/repository/RoleRepo.java
  src/main/java/ca/group20/sysc4806project/service/RoleService.java
  src/main/java/ca/group20/sysc4806project/service/RoleServiceImpl.java
  src/main/java/ca/group20/sysc4806project/service/SurveyorService.java
  src/main/java/ca/group20/sysc4806project/service/SurveyorServiceImpl.java
  src/main/java/ca/group20/sysc4806project/utility/TokenUtility.java
  src/test/java/ca/group20/sysc4806project/Sysc4806ProjectApplicationTests.java
  src/test/java/ca/group20/sysc4806project/controller/RespondentControllerTest.java
  src/test/java/ca/group20/sysc4806project/controller/SurveyorControllerTest.java
Labels: enhancement

#60 Added respondents endpoint to security config and removed WebConfig to fix CORS issue.
  src/main/java/ca/group20/sysc4806project/config/SecurityConfig.java
  src/main/java/ca/group20/sysc4806project/config/WebConfig.java
  src/main/java/ca/group20/sysc4806project/filter/CustomAuthorizationFilter.java
Labels: bug, enhancement

#61 Added missing endpoints to SecurityConfig and fixed tests.
  src/main/java/ca/group20/sysc4806project/config/SecurityConfig.java
  src/main/java/ca/group20/sysc4806project/filter/CustomAuthorizationFilter.java
  src/test/java/ca/group20/sysc4806project/controller/RespondentControllerTest.java
  src/test/java/ca/group20/sysc4806project/controller/SurveyorControllerTest.java
Labels: bug, enhancement

#62 trying to fix CORS
  src/main/java/ca/group20/sysc4806project/config/SecurityConfig.java
Labels: bug

#63 Doc/marianne/56
  README.md
  docs/AnswerSurvey.png
  docs/Authentication1.png
  docs/Authentication2.png
  docs/CreateSurvey.png
  docs/Models.png
  docs/Models.puml
Labels: documentation

#64 Fix Models
  docs/Models.png
  docs/Models.puml
Labels: documentation

#65 Fix db schema
  README.md
  docs/DatabaseSchema.PNG
  docs/DatabaseSchema.png
Labels: documentation

#68 Roles are now unique and no duplicates are allowed anymore
  src/main/java/ca/group20/sysc4806project/service/RoleService.java
  src/main/java/ca/group20/sysc4806project/service/RoleServiceImpl.java
Labels: bug

#70 Removed the need for JWT to be passed for specific endpoints that do not need it.
  src/main/java/ca/group20/sysc4806project/config/SecurityConfig.java
  src/main/java/ca/group20/sysc4806project/filter/CustomAuthorizationFilter.java
  src/test/java/ca/group20/sysc4806project/controller/SurveyorControllerTest.java
Labels: bug
